# {{TITLE}} — data provenance

`{{output}}.json` is generated by `_build.py` (re-run: `python3 _build.py`).
Snapshot taken {{ISO timestamp}}.

## Tier key

- **A** — primary. The agency that owns the data, publishing it directly.
- **B** — aggregator republishing government data.
- **C** — community or crowdsourced.
- **D** — could not fetch, could not verify, or provenance unclear.

## Sources

### {{Source name}} — Tier {{A}}

- **Endpoint:** `{{url}}`
- **Publisher:** {{agency}}
- **Cadence:** {{hourly / daily / annual / static}}
- **API key:** {{none / required — see below}}
- **Verified:** {{YYYY-MM-DD}}, returned **{{N}}** records inside the bbox
- **Fields used:** `{{FIELD}}` → `{{our field}}`, ...
- **Coordinate system:** {{WGS84 / reprojected from ...}}
- **License:** {{...}}

**What the source does not have:** {{Fields we wanted and could not get. This
list is why certain things are missing from the UI. Never fabricate these.}}

**Transformations:** {{decimation, unit conversion, bucketing, filtering}}

## Real vs illustrative

{{Exact count of each. Which layers are real, which are placeholders, and how a
reader can tell them apart in the interface itself. If everything is real, say
"All {{N}} records are real" and delete the rest of this section.}}

## Could not verify

{{Any source we tried and failed to reach, and what we did about it: dropped, or
drawn and labeled. If nothing, write "Nothing — every layer drawn was fetched
and counted."}}

## API keys

{{If a source needs one:}}
- Sign up: {{url}}
- Env var: `{{VAR_NAME}}` in `.env.local`
- Currently: {{using keyless fallback X / live}}

## Production path

{{What it would take to move this from snapshot to live, or from illustrative to
real, layer by layer. The UI should need no changes — that is the test of a good
normalization in `types.ts`.}}
